### ISSUE TITLE
Restore cache step fails with restoreKeys.join() is not a function

### ISSUE THREAD

**Issue by elijahr** [ktmud/cached-dependencies#73]
The README suggests using `ktmud/cached-dependencies@v1`, which throws an error:

```
RESTORE cache for npm
  (node:4925) UnhandledPromiseRejectionWarning: TypeError: restoreKeys.join is not a function
      at /home/runner/work/_actions/ktmud/cached-dependencies/v1/dist/scripts/cache/index.js:5170:99
      at Generator.next (<anonymous>)
      at fulfilled (/home/runner/work/_actions/ktmud/cached-dependencies/v1/dist/scripts/cache/index.js:5048:58)
  (Use `node --trace-warnings ...` to show where the warning was created)
  (node:4925) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
  (node:4925) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The build proceeds, but it seems that caching is broken. I can't find references to `restoreKeys.join` in master or in the v1.1 tag, so the issue appears to be fixed, though the README still suggests using an unfixed version of the action.

What I've often seen done with Github Actions is that `v1` would be a branch rather than a tag, and the latest `v1.X.X` tags would be merged into that branch. So users of `ktmud/cached-dependencies@v1` would always have the most up-to-date code for that major version. As you release v1.2, etc, those tags would get merged into the v1 branch.

So I think the fix here would be one of these two options:

1. Delete the `v1` tag and replace it with a `v1` branch based on the `v1.1` tag
2. Update the README so folks don't use the `v1`  tag

Option 1 seems more ideal.

Cheers! Great plugin.

**Comment by ktmud** [comment]
Good call on creating `v1` as a branch. I'll update.

**Comment by ktmud** [comment]
Updated.
